version: '3'
services:
  server:
    image: node:14
    ports :
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - database
    networks:
      - db
      - exterior
    command: npm start

  database:
    image: postgres:9.6-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      - db

  adminer:
    image: adminer:standalone
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - db
      - exterior

networks:
  exterior:
    internal: false
  db:
    internal: true

